import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Script from "next/script";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Script src = "/sc.js" strategy="lazyOnLoad"></Script>
      <main className={`${styles.main} ${inter.className}`}>
        <nav className={styles.mainnav}>
          <ul className={styles.navlist}>
            
            <Link href="/"><li>Home</li></Link>
            <Link href="/about"><li>About</li></Link>
            <Link href="/blog"><li>Blog</li></Link>
            <Link href="/contact"><li>Contact</li></Link>
          </ul>
        </nav>

        <div className={styles.center} style={{ flexDirection: "column" , gap:"2rem"}}>
          <h1 className={styles.code}>Hunting Coder</h1>
          <div className={styles.description}>
            <p>A Blog for Coders by Coders</p>
          </div>
        </div>
        
        <div className="blogs">
          <h1>Popular Blogs</h1>
          <br></br>
          <div className="blogItem">
            <h2>How to Learn JavaScript in  2023</h2>
            <p>JavaScript is the language ised to design logic for the Web</p>
          </div>
          <br></br>
          <div className="blogItem">
            <h2>How to Learn JavaScript in  2023</h2>
            <p>JavaScript is the language ised to design logic for the Web</p>
          </div>
          <br></br>
          <div className="blogItem">
            <h2>How to Learn JavaScript in  2023</h2>
            <p>JavaScript is the language ised to design logic for the Web</p>
          </div>
        </div>
        <br />

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          
          </a>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
